version: '3.3'

services:
  auth_server:
    build: ./auth_server
    image: auth_server:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8499:8000"
    env_file:
      - ./auth_server/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1

  ai_dart_scraper:
    build: ./ai_dart_scraper
    image: ai_dart_scraper:1.0.0
    restart: unless-stopped # 컨테이너가 종료되지 않는 한 항상 재시작
    ports:
      - "8502:8080"
    env_file:
      - ./ai_dart_scraper/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 1
